---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

# - name: Copy MySQL Configuration
#   files:
#     src: my.cnf.j2
#     dest: /etc/mysql/my.cnf
#     owner: root
#     group: root
#     mode: '0644'

- name: Restart MySQL Service
  service:
    name: mysql
    state: restarted