---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Copy MySQL Configuration
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: '0644'

- name: Restart MySQL Service
  service:
    name: mysql
    state: restarted
